### ISSUE TITLE
another 1.15.2 Bug but smaller 

### ISSUE THREAD

**Issue by Jachimoo** [keksexception/LobbyNPCs#6] opened 2020-05-25 08:24 UTC
**Describe the bug**
if you trying to reload server with plugin its kicking you
**To Reproduce**
1. Have server 1.15.2 with this plugin
2. try to reload server! (not plugin)
3. 
4. 

**Console log**
[10:17:44 INFO]: Kaiser lost connection: Internal Exception: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
info:**
 - Pluginversion 1.1.-r3
 - PluginLib version 1.1-4b
 - Server version 1.15.2
 - Java version 8

**Installed plugins**
DeluxeHub
EasyPrefix
EssentialsX
LoginSecurity
LuckPerms
PlaceholderApi
PluginConstructorApi
ViaVersions
Worldedit
worldguard
WorldeditselectionVisualizer
Ajparkour

**Additional context**
minecraft says 
[Proxy] lost connection to the server

**Comment by keksexception** [comment] 2020-05-25 12:00
Hi, 
Thanks for your bug-report.
That error is caused by PluginLib. It will be fixed in the next version.

**Closed as completed** 2020-08-13 10:28 UTC
Labels: bug, Issuse, fixed, closed
